version: "2"
services:
  haproxy:
    image: eeacms/haproxy
    ports:
    - 80:5000
    - 1936:1936
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"

  plone:
    image: eeacms/kgs
    depends_on:
    - zeoserver
    - memcached
    - postfix
    environment:
    - ZOPE_MODE=zeo_client

  async:
    image: eeacms/kgs
    depends_on:
    - zeoserver
    - memcached
    - postfix
    environment:
    - ZOPE_MODE=zeo_async

  zeoserver:
    image: eeacms/kgs
    volumes:
    - zeo-data:/data
    environment:
    - ZOPE_MODE=zeoserver

  memcached:
    image: memcached:alpine
    command:
    - "memcached"
    - "-m"
    - "2048"

  postfix:
    image: eeacms/postfix
    environment:
    - MTP_HOST=eea.europa.eu

volumes:
  zeo-data:
