version: "2"
services:
  haproxy:
    image: eeacms/haproxy
    ports:
    - 80:5000
    - 1936:1936
    depends_on:
    - plone
    environment:
    - BACKENDS_PORT=8080
    - SERVICE_NAMES=plone

  plone:
    image: eeacms/kgs
    depends_on:
    - postgres
    - memcached
    - postfix
    environment:
    - ZOPE_MODE=rel_client

  async:
    image: eeacms/kgs
    depends_on:
    - postgres
    - memcached
    - postfix
    environment:
    - ZOPE_MODE=rel_async

  postgres:
    image: eeacms/postgres
    environment:
    - POSTGRES_DBNAME=datafs zasync
    - POSTGRES_DBUSER=zope
    - POSTGRES_DBPASS=zope
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres-data:/var/lib/postgresql/data

  memcached:
    image: memcached
    command:
    - "-m"
    - "2048"

  postfix:
    image: eeacms/postfix
    environment:
    - MTP_HOST=eea.europa.eu

volumes:
  postgres-data:
